OUTPUT_DIR = "results"
DEFAULT_POPULATION_SIZE = 100
DEFAULT_GENERATIONS = 100
DEFAULT_ELITE_SIZE = 2
DEFAULT_TOURNAMENT_SIZE = 5
DEFAULT_MUTATION_RATE = 0.1
MAX_STAGNANT_GENERATIONS_STOP = 30
STARTING_GENERATION_TO_CHECK_STAGNATION = 30